Vagrant.configure("2") do |config|

  config.vm.define "Init_System" do |init| 
    init.vm.box = "ubuntu/jammy64"
    init.vm.hostname = "init"
    init.vm.boot_timeout = 600
    init.vm.provider "virtualbox" do |vb|
      vb.name = "Init_S"
      vb.memory = 2048
      vb.cpus = 2
    end  
    init.vm.provision "shell", privileged: true, inline: <<-SHELL
      set -eu

      echo "==> Обновление системы"
      apt-get update
      apt-get upgrade -y
      echo "==> Установка пакетов"
      apt-get install -y \
      spawn-fcgi \
      php php-cgi php-cli \
      apache2 libapache2-mod-fcgid \
      nginx
      #-------------------------------------------------------------------------------------
      echo "==> Подготовка watchlog"
      mkdir -p /var/log
      touch /var/log/watchlog.log
      chmod 644 /var/log/watchlog.log

      # Добавляем тестовые строки
      cat > /var/log/watchlog.log <<'EOF'
INFO: Service started
INFO: Everything OK
ALERT: Something happened
EOF
      install -D -m 0644 /vagrant/watchlog/watchlog /etc/default/watchlog
      install -D -m 0755 /vagrant/watchlog/watchlog.sh /opt/watchlog.sh
      chmod +x /opt/watchlog.sh
      install -D -m 0644 /vagrant/watchlog/watchlog.service /etc/systemd/system/watchlog.service
      install -D -m 0644 /vagrant/watchlog/watchlog.timer /etc/systemd/system/watchlog.timer
      #-------------------------------------------------------------------------------------
      echo "==> Подготовка spawn-fcgi"
      mkdir -p /etc/spawn-fcgi
      install -D -m 0644 /vagrant/spawn-fcgi/fcgi.conf /etc/spawn-fcgi/fcgi.conf
      install -D -m 0755 /vagrant/spawn-fcgi/spawn-fcgi.service /etc/systemd/system/spawn-fcgi.service
      #-------------------------------------------------------------------------------------
      echo "==> Подготовка nginx"
      systemctl disable --now apache2
      systemctl disable --now nginx
      install -D -m 0644 /vagrant/nginx/nginx@.service /etc/systemd/system/nginx@.service
      install -D -m 0644 /vagrant/nginx/nginx-first.conf /etc/nginx/nginx-first.conf
      install -D -m 0644 /vagrant/nginx/nginx-second.conf /etc/nginx/nginx-second.conf

      echo "==> Включаем сервисы"
      systemctl daemon-reload
      systemctl enable --now watchlog.timer
      systemctl restart watchlog.timer
      systemctl restart spawn-fcgi
      systemctl status watchlog.timer --no-pager -l || true
      systemctl enable --now spawn-fcgi.service
      systemctl status spawn-fcgi --no-pager -l || true
      systemctl restart nginx@first
      systemctl restart nginx@second
      ss -tnulp | grep nginx

      SHELL
  end

end
