# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  master: {
    box_name: "ubuntu/jammy64",
    ip_addr: "192.168.11.150",
    prov_script: "provision/master.sh"
  },
  slave: {
    box_name: "ubuntu/jammy64",
    ip_addr: "192.168.11.151",
    prov_script: "provision/slave.sh"
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.hostname = boxname.to_s
      box.vm.boot_timeout = 600

      # Создаём приватную сеть между хостом и ВМ
      box.vm.network "private_network", ip: boxconfig[:ip_addr]

      box.vm.provider "virtualbox" do |vb|
        vb.name = "mysql-#{boxname}"
        vb.memory = 2048
        vb.cpus = 3
      end

      # Запускаем provisioning shell-скриптом
      box.vm.provision "shell",
        path: boxconfig[:prov_script],
        privileged: true       
    end
  end
end