# Берём официальный nginx на базе Alpine (маленький образ)
FROM nginx:alpine

# Копируем нашу страницу вместо дефолтной страницы nginx
# /usr/share/nginx/html/index.html — дефолтная страница nginx в этом образе
COPY index.html /usr/share/nginx/html/index.html
